### ISSUE TITLE
View User Roles & Permissions

### ISSUE THREAD

**Issue by WindOfRussia** [CSU-Booking-Platform/application#40]
### User story
As an administrator, I can see the roles that were assigned to other users of the system.

### Narrative
As an administrator, I want to see which roles were assigned to other users of the system, so I can track and manage user access to different areas of the application as well as the permissions granted to them.

### Out of scope
Editing the roles and permissions of any of the users. 

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an administrator|I try to view user roles index|The system lets me see all users, their roles and their permissions|
|2|I am not an administrator|I try to view user roles index|The system prevents me from viewing sensitive information|

**Comment by Alex-Hayeur** [comment]
UI for this is included in #42

**Comment by alecadub** [comment]
I think this issue is redundant ... View user roles were already tackled by #38 & PR #193!

View user permission .. is that really relevant? We want to see certain role permission (tackled by #36 ). 

We did a story before for assigning permissions directly to users, but we end-up labeling it as a won't fix (#35) 

What do you guys think @CSU-Booking-Platform/developers ?

**Comment by alexstojda** [comment]
Yeah good point @alecadub ok we'll close this for now.
